# ----------------------- #
#      Main Configs       #
# ----------------------- #

name : ejs-utils
description : Functions in javascript, jquery, jquery-ui, to help developers in simple situations of your workday.
author : emalherbi

menuHome :
  - name : Home
    link : 'home'
menu :
  - name : Usage
    link : 'usage'
  - name : Examples
    link : 'examples'
  - name : Test
    link : 'test'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown : kramdown
permalink : pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

github :
  - user : emalherbi
    repo : ejs-utils
